### ISSUE TITLE
Lacking Support for pandas Version 1.0.0

### ISSUE THREAD

**Issue by austensutherland** [Illumina/SpliceAI#35] opened 2020-02-05 02:09 UTC
### Summary
Went through a fresh install today and received the following error when running the command
` spliceai -I input.vcf -O output.vcf -R genome.fa -A grch38`

![image](https://user-images.githubusercontent.com/23382510/73805076-af000480-4793-11ea-9d9a-3af141b329a1.png)

Downgrading to the previous minor version (`0.25.3`) was functional but raised these deprecation warnings. 

![image](https://user-images.githubusercontent.com/23382510/73804435-ca6a1000-4791-11ea-9275-3ede02421549.png)

### Cause
Latest [pandas release](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.0.0.html) has deprecated support for the `get_values` method (seemily in place of `to_numpy` / `array` methods)

### Solution
Replace `get_values` calls witin the `__init__` of `Annotations` class with the pandas reccomended methods.

**Comment by Ptero64** [comment] 2020-02-10 16:34
Hello,

I would like to try SpliceAI but I have the same error. 
I don't understand how to do the fix you have indicated. Do we have to modify one of the python script? Or the easiestway is still to downgrad Pandas?

Thanks for the help,
Regards

**Comment by SandeepAswathnarayana** [comment] 2020-02-14 12:58
@austensutherland I believe replacing .get_values() with .to_numpy() at 7 different instances in utils.py (https://github.com/Illumina/SpliceAI/blob/master/spliceai/utils.py) should resolve this issue.

Also, the dependency on pandas needs to be upgraded from 'pandas>=0.23.0' to 'pandas>=0.24.2' if I am not mistaken.

I am curious to learn your inputs regarding the same!

**Comment by kishorejaganathan** [comment] 2020-02-15 23:01
Thank you @SandeepAswathnarayana for making the changes, I have merged the pull request and tested it.

@austensutherland, @Ptero64: If you clone the repo now, you should no longer run into this issue. Feel free to reopen the issue if you run into additional issues.

**Closed by kishorejaganathan** 2020-02-15 23:01 UTC

**Comment by wengkhong** [comment] 2020-03-04 07:59
@kishorejaganathan Thanks for fixing this issue in the repo. Would it be possible to deploy this fix to the bioconda recipe for spliceAI too?

**Comment by kishorejaganathan** [comment] 2020-03-04 08:56
Yes, will take care of it shortly.

**Comment by kishorejaganathan** [comment] 2020-03-08 13:04
The issue is now fixed for conda/pip installations as well (version 1.3.1).

**Comment by wengkhong** [comment] 2020-03-08 13:11
That was quick. Appreciate it!
