### ISSUE TITLE
Problems running

### ISSUE THREAD

**Issue by bopohdr** [Illumina/SpliceAI#5] opened 2019-02-11 00:07 UTC
I am running command:  `spliceai -I 4-ZL2487_S31_L001_001.vcf -O 2487_output.vcf -R ucsc_hg19.fa -A GENCODE.v24lift37`

and getting warning: 
```
Using TensorFlow backend.
2019-02-11 00:29:47.295532: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/usr/local/lib/python2.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
```

And then I have output for all variants : 
`... SpliceAI=G|.|.|.|.|.|.|.|.|. ...`

Example of VCF used:

```
##fileformat=VCFv4.2 |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
##FILTER=<ID=PASS,Description="All filters passed"> |   |   |  
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth"> |   |  
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality"> |   |  
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype"> |   |  
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="The phred-scaled genotype likelihoods rounded to the closest integer">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=BaseQRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt Vs. Ref base qualities">
##INFO=<ID=ClippingRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref number of hard clipped bases">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP membership"> |   |  
##INFO=<ID=DP,Number=1,Type=Integer,Description="Combined depth across samples"> |  
##INFO=<ID=ExcessHet,Number=1,Type=Float,Description="Phred-scaled p-value for exact test of excess heterozygosity">
##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">
##INFO=<ID=InbreedingCoeff,Number=1,Type=Float,Description="Inbreeding coefficient as estimated from the genotype likelihoods per-sample when compared against the Hardy-Weinberg expectation">
##INFO=<ID=MLEAC,Number=A,Type=Integer,Description="Maximum likelihood expectation (MLE) for the allele counts, for each ALT allele, in the same order as listed">
##INFO=<ID=MLEAF,Number=A,Type=Float,Description="Maximum likelihood expectation (MLE) for the allele frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=MQ,Number=1,Type=Float,Description="RMS mapping quality"> |   |  
##INFO=<ID=MQRankSum,Number=1,Type=Float,Description="Z-score From Wilcoxon rank sum test of Alt vs. Ref read mapping qualities">
##INFO=<ID=QD,Number=1,Type=Float,Description="Variant Confidence/Quality by Depth">
##INFO=<ID=ReadPosRankSum,Number=1,Type=Float,Description="Z-score from Wilcoxon rank sum test of Alt vs. Ref read position bias">
##INFO=<ID=SOR,Number=1,Type=Float,Description="Symmetric Odds Ratio of 2x2 contingency table to detect strand bias">
##SentieonCommandLine.GVCFtyper=<ID=GVCFtyper,Version="sentieon-genomics-201808",Date="2018-12-06T09:10:32Z",CommandLine="/usr/local/sentieon-genomics-201808/libexec/driver --interval ignore_decoy.bed -r genome/ucsc_hg19.fa -t 32 --algo GVCFtyper --call_conf 20 --emit_conf 20 -v output.g.vcf.gz -d resources/dbsnp_138.hg19.vcf.gz output.vcf.gz">
##SentieonCommandLine.Haplotyper=<ID=Haplotyper,Version="sentieon-genomics-201808",Date="2018-12-06T09:07:16Z",CommandLine="/usr/local/sentieon-genomics-201808/libexec/driver --interval ignore_decoy.bed -r genome/ucsc_hg19.fa -t 32 -i realigned.bam -q recal_data.table --algo Haplotyper --call_conf 20 --emit_conf 20 --phmm_chunk_size 1000 --emit_mode gvcf -d resources/dbsnp_138.hg19.vcf.gz output.g.vcf.gz">
##contig=<ID=chrM,length=16571,assembly=hg19> |   |   |   |  
##contig=<ID=chr1,length=249250621,assembly=hg19> |   |   |  
##contig=<ID=chr2,length=243199373,assembly=hg19> |   |   |  
##contig=<ID=chr3,length=198022430,assembly=hg19> |   |   |  
##contig=<ID=chr4,length=191154276,assembly=hg19> |   |   |  
##contig=<ID=chr5,length=180915260,assembly=hg19> |   |   |  
##contig=<ID=chr6,length=171115067,assembly=hg19> |   |   |  
##contig=<ID=chr7,length=159138663,assembly=hg19> |   |   |  
##contig=<ID=chr8,length=146364022,assembly=hg19> |   |   |  
##contig=<ID=chr9,length=141213431,assembly=hg19> |   |   |  
##contig=<ID=chr10,length=135534747,assembly=hg19> |   |   |  
##contig=<ID=chr11,length=135006516,assembly=hg19> |   |   |  
##contig=<ID=chr12,length=133851895,assembly=hg19> |   |   |  
##contig=<ID=chr13,length=115169878,assembly=hg19> |   |   |  
##contig=<ID=chr14,length=107349540,assembly=hg19> |   |   |  
##contig=<ID=chr15,length=102531392,assembly=hg19> |   |   |  
##contig=<ID=chr16,length=90354753,assembly=hg19> |   |   |  
##contig=<ID=chr17,length=81195210,assembly=hg19> |   |   |  
##contig=<ID=chr18,length=78077248,assembly=hg19> |   |   |  
##contig=<ID=chr19,length=59128983,assembly=hg19> |   |   |  
##contig=<ID=chr20,length=63025520,assembly=hg19> |   |   |  
##contig=<ID=chr21,length=48129895,assembly=hg19> |   |   |  
##contig=<ID=chr22,length=51304566,assembly=hg19> |   |   |  
##contig=<ID=chrX,length=155270560,assembly=hg19> |   |   |  
##contig=<ID=chrY,length=59373566,assembly=hg19> |   |   |  
##contig=<ID=chr1_gl000191_random,length=106433,assembly=hg19> |   |  
##contig=<ID=chr1_gl000192_random,length=547496,assembly=hg19> |   |  
##contig=<ID=chr4_ctg9_hap1,length=590426,assembly=hg19> |   |   |  
##contig=<ID=chr4_gl000193_random,length=189789,assembly=hg19> |   |  
##contig=<ID=chr4_gl000194_random,length=191469,assembly=hg19> |   |  
##contig=<ID=chr6_apd_hap1,length=4622290,assembly=hg19> |   |   |  
##contig=<ID=chr6_cox_hap2,length=4795371,assembly=hg19> |   |   |  
##contig=<ID=chr6_dbb_hap3,length=4610396,assembly=hg19> |   |   |  
##contig=<ID=chr6_mann_hap4,length=4683263,assembly=hg19> |   |  
##contig=<ID=chr6_mcf_hap5,length=4833398,assembly=hg19> |   |   |  
##contig=<ID=chr6_qbl_hap6,length=4611984,assembly=hg19> |   |   |  
##contig=<ID=chr6_ssto_hap7,length=4928567,assembly=hg19> |   |   |  
##contig=<ID=chr7_gl000195_random,length=182896,assembly=hg19> |   |  
##contig=<ID=chr8_gl000196_random,length=38914,assembly=hg19> |   |  
##contig=<ID=chr8_gl000197_random,length=37175,assembly=hg19> |   |  
##contig=<ID=chr9_gl000198_random,length=90085,assembly=hg19> |   |  
##contig=<ID=chr9_gl000199_random,length=169874,assembly=hg19> |   |  
##contig=<ID=chr9_gl000200_random,length=187035,assembly=hg19> |   |  
##contig=<ID=chr9_gl000201_random,length=36148,assembly=hg19> |   |  
##contig=<ID=chr11_gl000202_random,length=40103,assembly=hg19> |   |  
##contig=<ID=chr17_ctg5_hap1,length=1680828,assembly=hg19> |   |  
##contig=<ID=chr17_gl000203_random,length=37498,assembly=hg19> |   |  
##contig=<ID=chr17_gl000204_random,length=81310,assembly=hg19> |   |  
##contig=<ID=chr17_gl000205_random,length=174588,assembly=hg19> |   |  
##contig=<ID=chr17_gl000206_random,length=41001,assembly=hg19> |   |  
##contig=<ID=chr18_gl000207_random,length=4262,assembly=hg19> |   |  
##contig=<ID=chr19_gl000208_random,length=92689,assembly=hg19> |   |  
##contig=<ID=chr19_gl000209_random,length=159169,assembly=hg19> |   |  
##contig=<ID=chr21_gl000210_random,length=27682,assembly=hg19> |   |  
##contig=<ID=chrUn_gl000211,length=166566,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000212,length=186858,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000213,length=164239,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000214,length=137718,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000215,length=172545,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000216,length=172294,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000217,length=172149,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000218,length=161147,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000219,length=179198,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000220,length=161802,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000221,length=155397,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000222,length=186861,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000223,length=180455,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000224,length=179693,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000225,length=211173,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000226,length=15008,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000227,length=128374,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000228,length=129120,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000229,length=19913,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000230,length=43691,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000231,length=27386,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000232,length=40652,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000233,length=45941,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000234,length=40531,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000235,length=34474,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000236,length=41934,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000237,length=45867,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000238,length=39939,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000239,length=33824,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000240,length=41933,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000241,length=42152,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000242,length=43523,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000243,length=43341,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000244,length=39929,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000245,length=36651,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000246,length=38154,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000247,length=36422,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000248,length=39786,assembly=hg19> |   |   |  
##contig=<ID=chrUn_gl000249,length=38502,assembly=hg19> |   |   |  
##reference=file://genome/ucsc_hg19.fa |   |   |   |  
##INFO=<ID=SpliceAI,Number=.,Type=String,Description="SpliceAI variant annotation. These include delta scores (DS) and delta positions (DP) for acceptor gain (AG), acceptor loss (AL), donor gain (DG), and donor loss (DL). Format: ALLELE\|SYMBOL\|DS_AG\|DS_AL\|DS_DG\|DS_DL\|DP_AG\|DP_AL\|DP_DG\|DP_DL">
#CHROM | POS | ID | REF | ALT | QUAL | FILTER | INFO
chrM | 195 | . | C | T | 725.77 | . | AC=2;AF=1;AN=2;DP=25;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=29.03;SOR=0.941;SpliceAI=T\|.\|.\|.\|.\|.\|.\|.\|.\|.
chrM | 302 | . | A | AC | 77 | . | AC=2;AF=1;AN=2;DP=4;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=60;QD=19.25;SOR=3.258;SpliceAI=AC\|.\|.\|.\|.\|.\|.\|.\|.\|.
```

 I am able to produce the right results for the example input VCF. Although having the abovementioned message about that model is not compiled.

**Comment by kishorejaganathan** [comment] 2019-02-11 02:16
The issue is due to the fact that your VCFs have chromosomes named chr1, chr2, ... but the annotation file has chromosomes named 1, 2, ... and so on. This will be fixed in the next release. Meanwhile, you can try removing the chr strings in the input file and try it out (or add chr strings to the chromosome names in the annotation file).

**Comment by bopohdr** [comment] 2019-02-11 02:38
Thank You. 
Although changing chr1 --> 1 in VCF via excell or textmanager results in:
```
Using TensorFlow backend.
[E::vcf_hdr_read] No sample line
Traceback (most recent call last):
  File "/usr/local/bin/spliceai", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/spliceai/__main__.py", line 46, in main
    vcf = pysam.VariantFile(args.I)
  File "pysam/libcbcf.pyx", line 4015, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4251, in pysam.libcbcf.VariantFile.open
ValueError: file `<open file '/Users/dmitrijsrots/Downloads/4-ZL2487_S31_L001_001.vcf', mode 'rt' at 0x12dba1540>` does not have valid header (mode=`r`) - is it VCF/BCF format?
```
So obviously spliceai to not like when something is done to VCF.

While changing 1-->chr1 in annotation file (GENCODE.v24lift37) results in : 

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/spliceai", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/spliceai/__main__.py", line 50, in main
    ann = annotator(args.R, args.A)
  File "/usr/local/lib/python2.7/site-packages/spliceai/utils.py", line 18, in __init__
    self.chroms = df['CHROM'].get_values()
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CHROM'
```

Do You have any suggestions how to edit VCF efficiently so spliceai would except it? 
And is it possible to add support for .tsv type of files ? 

Thank You !

**Comment by kishorejaganathan** [comment] 2019-02-11 16:32
Changing VCF files in Excel is generally problematic. I would recommend sed. For example:

`sed 's/chr//g' infile.vcf > outfile.vcf`

**Comment by bopohdr** [comment] 2019-02-11 21:55
> Changing VCF files in Excel is generally problematic. I would recommend sed. For example:
> 
> `sed 's/chr//g' infile.vcf > outfile.vcf`

Thank You ! That helped with VCF, although now I am getting a new error:

```
Using TensorFlow backend.
2019-02-11 22:43:38.105656: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/usr/local/lib/python2.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "/usr/local/bin/spliceai", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/spliceai/__main__.py", line 53, in main
    scores = get_delta_scores(record, ann)
  File "/usr/local/lib/python2.7/site-packages/spliceai/utils.py", line 139, in get_delta_scores
    idx_pA = (Y[1, :, 1]-Y[0, :, 1]).argmax()
ValueError: attempt to get argmax of an empty sequence
```

**Comment by kishorejaganathan** [comment] 2019-02-11 22:02
Does this happen to the very first variant, or a few variants get annotated and then you run into this error? Can you check the output file and let me know?

**Comment by bopohdr** [comment] 2019-02-11 22:03
Nothing gets annotated

**Comment by kishorejaganathan** [comment] 2019-02-11 22:10
I just checked the logs above to find the first variant. This makes sense, it turns out that the software in its current form cannot annotate variants in the first and last 5,000 positions of a chromosome as the input length does not match. If you could take those out for now, you should be fine. I'll fix this in the next version (probably will be pushed later this week). Alternately, you can check out the file with precomputed scores for all SNVs (link provided in the README) in the genic regions.

**Comment by bopohdr** [comment] 2019-02-13 00:05
Thank You ! That worked.

**Closed** 2019-02-13 00:47 UTC
